{% set name = "changelog-chug" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/changelog_chug-{{ version }}.tar.gz
  sha256: 98ee1e8be75b6e9d512c35292c3c293a124541a4ec2014a6ec3cf33a3d265d2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62.4.0
    - semver >=3.0.0
    - docutils >=0.21.0
    - pip
  run:
    - python >={{ python_min }}
    - semver >=3.0.0
    - docutils >=0.21.0

test:
  imports:
    - chug
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://git.sr.ht/~bignose/changelog-chug
  summary: Parser library for project Change Log documents.
  dev_url: https://git.sr.ht/~bignose/changelog-chug
  license: AGPL-3.0
  license_file:
    - LICENSE.AGPL-3
    - COPYING

extra:
  recipe-maintainers:
    - xylar
